# Generated by Django 3.2.16 on 2023-03-28 03:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=75, unique=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(max_length=75)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceKey',
            fields=[
                ('device_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_eui', models.CharField(max_length=75, unique=True)),
                ('app_eui', models.CharField(max_length=75)),
                ('app_key', models.CharField(max_length=75)),
                ('claimed_status', models.CharField(choices=[('claimed', 'Claimed'), ('unclaimed', 'Unclaimed')], default='unclaimed', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
